<?= $this->headTitle('Blog') ?>
<h1>Blog</h1>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($posts as $post): ?>
            <tr>
                <td><?= $this->escapeHtml($post->title) ?></td>
                <td><?= $this->escapeHtml($post->content) ?></td>
                <td></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>